services:
  db:
    image: postgres:15
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    working_dir: /code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: .env

  bot:
    build:
      context: .
    volumes:
      - .:/app
    working_dir: /app/bot
    command: ["python", "main.py"]
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:

#version: "3.9"
#
#services:
#  db:
#    image: postgres:15
#    env_file: .env
#    environment:
#      POSTGRES_DB: ${POSTGRES_DB}
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    ports:
#      - "5433:5432"
#
#  web:
#    build: .
#    command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - .:/code
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db
#    env_file: .env
#
#  bot:
#    build:
#      context: ./bot
#      dockerfile: Dockerfile
#    volumes:
#      - .:/code
#    working_dir: /code/bot
#    command: ["python", "main.py"]
#    depends_on:
#      - web
#    env_file:
#      - .env
#
#volumes:
#  postgres_data:

#version: '3.9'
#
#services:
#  db:
#    image: postgres:15
#    env_file: .env
#    environment:
#      POSTGRES_DB: ${POSTGRES_DB}
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    ports:
#      - "5433:5432"
#
#  web:
#    build: .
#    command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - .:/code
#    working_dir: /code
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db
#    env_file: .env
#
#  bot:
#    build:
#      context: .              # 👈 корень проекта, а не ./bot
#    volumes:
#      - .:/app                # 👈 весь проект
#    working_dir: /app/bot     # 👈 запуск из папки bot
#    command: ["python", "main.py"]
#    depends_on:
#      - db
#    env_file:
#      - .env
#
#volumes:
#  postgres_data:


#
#services:
#  db:
#    image: postgres:15
#    env_file: .env
#    environment:
#      POSTGRES_DB: ${POSTGRES_DB}
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    ports:
#      - "5433:5432"
#
#  web:
#    build: .
#    command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - .:/code
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db
#    env_file: .env
#
#  bot:
#    build:
#      context: ./bot
#    volumes:
#      - ./bot:/app
#    working_dir: /app
#    command: ["python", "main.py"]
#    depends_on:
#      - db
#    env_file:
#      - .env
#
#
#volumes:
#  postgres_data:
